---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: instance
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    published_ports:
      - 9090:9090
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - prometheues
    docker_networks:
      - name: prom
        ipam_config:
          - subnet: "10.18.0.0/24"
            gateway: "10.18.0.254"
    networks:
      - name: prom
        ipv4_address: "10.18.0.1"

  - name: federated
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    published_ports:
      - 9091:9090
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - prometheues
    networks:
      - name: prom
        ipv4_address: "10.18.0.2"


provisioner:
  name: ansible
  ansible_args:
    - --diff
    # - -vv
  config_options:
    defaults:
      deprecation_warnings: True
      stdout_callback: yaml

scenario:
  test_sequence:
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
