---

- block:
    - name: get checksum list
      set_fact:
        __prometheus_checksums: "{{ lookup('url', 'https://github.com/prometheus/prometheus/releases/download/v' + prometheus_version + '/sha256sums.txt', wantlist=True) | list }}"
      run_once: true

    - name: get checksum for {{ go_arch }} architecture
      set_fact:
        __prometheus_checksum: "{{ __prometheus_checksums | prometheus_checksum('linux', go_arch) }}"
  delegate_to: localhost

- name: download prometheus binary archive
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  get_url:
    url: "{{ prometheus_release_download_url }}/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_local_tmp_directory }}/prometheus-linux-amd64.tar.gz"
    checksum: "sha256:{{ __prometheus_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract prometheus archive
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  unarchive:
    src: "{{ prometheus_local_tmp_directory }}/prometheus-linux-amd64.tar.gz"
    dest: "{{ prometheus_local_tmp_directory }}"
    copy: false
  register: _extract_archive

...
