---

- name: detect binary file for prometheus
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  stat:
    path: "{{ prometheus_local_tmp_directory }}/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
  register: stat_file_binary

- block:
    - name: propagate prometheus binaries
      copy:
        src: "{{ prometheus_local_tmp_directory }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "{{ prometheus_install_path }}/{{ item }}"
        mode: 0755
        owner: "{{ prometheus_system_user }}"
        group: "{{ prometheus_system_group }}"
        remote_src: "{{ 'true' if prometheus_direct_download else 'false' }}"
      loop:
        - prometheus
        - promtool

    - name: make files executable
      file:
        path: "{{ prometheus_install_path }}/{{ item }}"
        mode: 0755
        owner: "{{ prometheus_system_user }}"
        group: "{{ prometheus_system_group }}"
      loop:
        - prometheus
        - promtool
  when:
    - stat_file_binary.stat.exists

- name: propagate official console templates
  copy:
    src: "{{ prometheus_local_tmp_directory }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: 0644
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
  loop:
    - console_libraries
    - consoles
  notify:
    - reload prometheus

- name: create local facts
  template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/prometheus.fact
    mode: 0755

- name: create link to binary
  file:
    src: "{{ prometheus_install_path }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: true
    follow: false
  loop:
    - prometheus
    - promtool
  notify:
    - restart prometheus

- name: create prometheus data directory
  file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0755

- name: openrc
  block:

    - name: create systemd service unit
      template:
        src: "init/systemd/prometheus.service.j2"
        dest: "{{ systemd_lib_directory }}/prometheus.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart prometheus

    - name: create prometheus run configuration
      template:
        src: "prometheus.j2"
        dest: "{{ prometheus_defaults_directory }}/prometheus"
        force: true
        owner: root
        group: "{{ prometheus_system_group }}"
        mode: 0640
      notify:
        - validate config
        - reload prometheus
  when:
    - ansible_service_mgr | lower == "systemd"

- name: openrc
  block:
    - name: create openrc service configuration
      template:
        src: "init/openrc/conf.d/prometheus.j2"
        dest: "/etc/conf.d/prometheus"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      template:
        src: "init/openrc/init.d/prometheus.j2"
        dest: "/etc/init.d/prometheus"
        owner: root
        group: root
        mode: 0750
  when:
    - ansible_service_mgr | lower == "openrc"

- name: create rules directory
  file:
    state: directory
    path: "{{ prometheus_config_dir }}/rules"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

- name: create targets directory
  file:
    state: directory
    path: "{{ prometheus_config_dir }}/targets"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

- name: create file_sd directory
  file:
    state: directory
    path: "{{ prometheus_config_dir }}/file_sd"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

...
