---

- name: detect binary file for prometheus
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  run_once: "{{ 'false' if prometheus_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ prometheus_local_tmp_directory }}/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
  register: stat_file_binary

- name: propagate files
  when:
    - stat_file_binary.stat.exists
  block:
    - name: propagate prometheus binaries
      ansible.builtin.copy:
        src: "{{ prometheus_local_tmp_directory }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "{{ prometheus_install_path }}/{{ item }}"
        mode: 0755
        owner: "{{ prometheus_system_user }}"
        group: "{{ prometheus_system_group }}"
        remote_src: "{{ 'true' if prometheus_direct_download else 'false' }}"
      loop:
        - prometheus
        - promtool

    - name: propagate official console templates
      ansible.builtin.copy:
        src: "{{ prometheus_local_tmp_directory }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
        dest: "{{ prometheus_config_dir }}/{{ item }}/"
        mode: 0644
        owner: "{{ prometheus_system_user }}"
        group: "{{ prometheus_system_group }}"
        remote_src: "{{ 'true' if prometheus_direct_download else 'false' }}"
      loop:
        - console_libraries
        - consoles
      notify:
        - reload prometheus

- name: make files executable
  ansible.builtin.file:
    path: "{{ prometheus_install_path }}/{{ item }}"
    mode: 0755
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
  loop:
    - prometheus
    - promtool

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/prometheus.fact
    mode: 0755

- name: create link to binary
  ansible.builtin.file:
    src: "{{ prometheus_install_path }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: true
    follow: false
  loop:
    - prometheus
    - promtool
  notify:
    - restart prometheus

- name: create prometheus data directory
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0755

- name: create rules directory
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_config_dir }}/rules"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

- name: create targets directory
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_config_dir }}/targets"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

- name: create file_sd directory
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_config_dir }}/file_sd"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/prometheus.service.j2"
        dest: "{{ systemd_lib_directory }}/prometheus.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart prometheus

    - name: create prometheus run configuration
      ansible.builtin.template:
        src: "prometheus.j2"
        dest: "{{ prometheus_defaults_directory }}/prometheus"
        force: true
        owner: root
        group: "{{ prometheus_system_group }}"
        mode: 0640
      notify:
        - validate config
        - reload prometheus

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/prometheus.j2"
        dest: "/etc/conf.d/prometheus"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/prometheus.j2"
        dest: "/etc/init.d/prometheus"
        owner: root
        group: root
        mode: 0750

...
