---

- name: restart prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: reload prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: reloaded

- name: validate config  # noqa command-instead-of-module
  ansible.builtin.command: |
    /usr/bin/promtool check config {{ prometheus_config_dir }}/prometheus.yml

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: summary of changes or failed
  ansible.builtin.debug:
    msg: "{{ _created_alert_rules }}"
  when:
    - _created_alert_rules.changed or
      _created_alert_rules.failed

...
