---

- name: restart prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: restarted
  when:
    - prometheus_valid_config is defined
    - prometheus_valid_config.rc is defined
    - prometheus_valid_config.rc == 0

- name: reload prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: reloaded

- name: validate config
  promtool:
    state: check
    config: "{{ prometheus_config_dir }}/prometheus.yml"
  register: prometheus_valid_config
  notify:
    - restart prometheus

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: summary of changes or failed
  ansible.builtin.debug:
    msg: "{{ _created_alert_rules }}"
  when:
    - _created_alert_rules.changed or
      _created_alert_rules.failed

...
