---

- name: restart prometheus
  become: true
  service:
    name: prometheus
    state: restarted

- name: reload prometheus
  become: true
  service:
    name: prometheus
    state: reloaded

# - name: validate config

- name: daemon-reload
  become: true
  systemd:
    daemon_reload: true
    force: true

...
