---

prometheus_service:
  log:
    level: debug

prometheus_global:
  scrape_interval: 5m
  evaluation_interval: 2m
  external_labels:
    environment: MOLECULE
    production: not

prometheus_alerting:
  alert_relabel_configs: []
  alertmanagers: []

#prometheus_rule_files:
#  - "foo.yml"
#  - bar.json
prometheus_scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  #
  - job_name: "grafana"
    static_configs:
      - targets:
        - "127.0.0.1:3000"
  # sensors
  - job_name: "sensors"
    file_sd_configs:
      - files:
        - file_sd/sensors.yaml
    relabel_configs:
      # remove port from instance name
      - source_labels:
          - __address__
        regex: "(.*):.*"
        replacement: $1
        target_label: instance
      # Extract the host ID (last octet of IPv4 address)
      - source_labels:
          - __address__
        regex: "sensor-(\\d+)..*"
        target_label: host_id
      # Set location label
      - source_labels:
          - host_id
        regex: "01"
        replacement: buero
        target_label: location
      # Set location label
      - source_labels:
          - host_id
        regex: "01"
        replacement: buero
        target_label: location
      - source_labels:
          - host_id
        regex: "02"
        replacement: titus
        target_label: location
      - source_labels:
          - host_id
        regex: "03"
        replacement: esszimmer
        target_label: location

      - source_labels:
          - host_id
        regex: "05"
        replacement: it-bunker
        target_label: location
  #
  - job_name: "kresd"
    file_sd_configs:
      - files:
        - file_sd/kresd.yaml



...
